name: Build SunamoCollectionsChangeContent

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCollectionsChangeContent
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionsChangeContent/SunamoCollectionsChangeContent.csproj

    - name: Build
      run: dotnet build SunamoCollectionsChangeContent/SunamoCollectionsChangeContent.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCollectionsChangeContent.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionsChangeContent.Tests/SunamoCollectionsChangeContent.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCollectionsChangeContent.Tests/SunamoCollectionsChangeContent.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCollectionsChangeContent.Tests/SunamoCollectionsChangeContent.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
